MOSTregi/MOSTregi/urls.py
# MOSTregi/urls

from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls import url
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView, TemplateView
from django.contrib.auth import views as auth_views

from . import views
from users import views as users_views

urlpatterns = [
    re_path(r'^favicon.ico$',
        RedirectView.as_view(
            url=staticfiles_storage.url('img/favicon/favicon.ico'),
            permanent=False),
        name="favicon"
    ),
    re_path(r'^$', TemplateView.as_view(template_name='home.html')),
    path('home/', TemplateView.as_view(template_name='home.html')),
    re_path(r'^admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', users_views.signup.as_view(), name='signup'),
    path('events/', include('events.urls', 'events')),
]

# =============================================
#  code graveyard
# =============================================
# from django.conf import settings
# from os import listdir, walk
# from os.path import *
#
# def files_from_dir(directory):
#     result = []
#     for root, directories, filenames in walk(directory):
#         for directory in directories:
#             print()
#         for filename in filenames:
#             result.append(filename)
#     return result
#
# def files_from_list_of_dir(dir_list):
#     result = []
#     if not dir_list:
#         return result
#     for folder in dir_list:
#         print("calling files_from_dir on ", folder)
#         result.extend(files_from_dir(folder))
#     return result

# what we actually want to do is generate a list of static files that end in .html
# and if (w/e).html fits it, call views.fetchHTML

MOSTregi/events/urls.py
# django imports
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls import url
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

# local imports
from . import views

app_name = 'events'

urlpatterns = [
    path('', views.events_landing, name="events_landing"),
    path('new/', views.new, name="new"),
    re_path(r'edit/(?P<pk>\d+)/', views.edit, name="edit"),
    re_path(r'delete/(?P<pk>\d+)/', views.delete, name="delete"),
    path('delete_all/', views.delete_all, name="delete_all"),
    re_path(r'show_detail/(?P<pk>\d+)/', views.show_detail, name="show_detail"),
    path('all/', views.list_all, name="list_all"),
    path('all/mine/', views.list_mine, name="list_mine"),
    #re_path(r'^([a-zA-Z/]{0,50})$', views.testCatch),
]

MOSTregi/users/urls.py
# MOSTregi/urls

from django.urls import path, re_path, include

urlpatterns = [

]

MOSTregi/templates/README.html
<h2>Event Manager</h2>

<h3>a simple visitor management software</h3>

<h4>by Esmeralda Quintana, Monti Wilkins, Edwin Bishop, Austin Schwartz, and Abbie Leonard</h4>

<h3>Current features:</h3>

<ul>
<li>this README</li>
<li>Can register events under "New Booking"</li>
<li>Users, Groups, BookingRequest model in admin page</li>
<li>Add/Edit/Delete functionality on webpage</li>
<li>View BookingRequest: individual, list, and list all created by current user</li>
<li>Basic user logins and signups</li>
<li>Add/Edit/Delete require individual permissions</li>
<li>User signups page requires permission</li>
<li>Adding event sends a confirmation email</li>
</ul>

<h3>Currently working on:</h3>

<ul>
<li>styling</li>
<li>booking functionality: add, edit, delete.
<ul>
<li>"needs confirmation" for anonymous bookings</li>
<li>easy views for booking information: this week, this month, etc</li>
<li>Museum Event handling: ability to see what bookings coincide with official museum events</li>
</ul></li>
<li>finishing this list...</li>
</ul>

<h3>Build Dependencies</h3>

<ul>
<li>Python3</li>
<li>pip3</li>
<li>Django &gt;=2</li>
<li>django-bootstrap3 &gt;=9</li>
<li>django-phonenumber-field &gt;=2.0</li>
</ul>

<h4>For building: please see dev_README.md in /MOSTregi</h4>

MOSTregi/templates/blank_block.html
{% extends 'index.html' %}

{% load staticfiles %}

{% block extrahead %}
{% endblock %}

{% block contentheader %}
<h1 style="font-family: 'Playfair Display', serif;"></h1>
{% endblock %}

{% block content %}
<html>
    <h1>Blank page!</h1>
</html>
{% endblock %}

MOSTregi/templates/error.html
{% extends 'index.html' %}

{% load staticfiles %}

{% block extrahead %}
{% endblock %}

{% block contentheader %}
<h1 style="font-family: 'Playfair Display', serif;">Uh oh!</h1>
{% endblock %}

{% block content %}
<html>
    <h1>{{ error }}</h1>
</html>
{% endblock %}

MOSTregi/templates/home.html
{% extends 'index.html' %}
{% load staticfiles %}

{% block extrahead %}
<link rel="stylesheet" href="{% static '/css/home.css' %}">
{% endblock %}

{% block contentheader %}
<h1>MOST History Event Manager:
  <span style="font-family: 'Noto Sans', sans-serif; font-weight: bold">a README</span>
</h1>
{% endblock %}

{% block content %}
<div class= "home">
  <p>For now, this homepage will serve as the README. <br>
  It will be a quick start guide later. Maybe. Or a login page. <br>
  Or whatever it wants to be. We just want the homepage to be happy.</p>

  {% include 'README.html' %}
</div>

{% endblock %}

MOSTregi/templates/index.html
<html>
  <head>
    {% load staticfiles %}
    {% load bootstrap3 %}
    <!-- favicon -->
    <link rel="shortcut icon" type="image/png" href="{% static '/img/favicon/favicon.ico' %}"/>
    <!-- css -->
    {% bootstrap_css %}
    <link rel="stylesheet" href="{% static '/css/index.css' %}">
    {% bootstrap_messages %}
    <!-- JS -->
    <script type="text/javascript" src="{% static '/js/jquery-3.3.1.js' %}"></script>
    {% bootstrap_javascript %}
    <script type="text/javascript">
      $(document).ready(function () {
        $('#sidebarCollapse').on('click', function () {
        $('#sidebar, #content').toggleClass('active');
        $('.collapse.in').toggleClass('in');
        $('a[aria-expanded=true]').attr('aria-expanded', 'false');
        });
      });
    </script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Museum of South Texas History</title>
    {% block extrahead %}
    {% endblock %}
  </head>

  <body>
    <!-- wrapper holds entire page -->
    <!-- (I don't remember why I did this but it's not hurting anything) -->
    <div class="wrapper">
      <!-- Sidebar Holder -->
      <nav id="sidebar">
        <div id="sidebar-header">
          <h3><b>MOST History Event Manager</b></h3>
        </div>
        <ul class="list-unstyled CTAs">
          {% if user.is_authenticated %}
            <p>Logged in. Hi {{ user.username }}!</p>
            <li><a href="{% url 'logout' %}" class="download">logout</a></li>
            <li><a href="{% url 'events:list_mine' %}" class="download">My Tours</a></li>
            {% if user.is_superuser %}
              <li><a href="{% url 'signup' %}" class="download">New Employee</a></li>
            {% endif %}
          {% else %}
            <p>You are not logged in</p>
            <li><a href="{% url 'login' %}" class="download">login</a></li>
          {% endif %}
          <li><a href="" class="download">_________</a></li>
          <li><a href="/" class="download">Home</a></li>
          <li><a href="{% url 'events:new' %}" class="download">New Tour</a></li>
          <li><a href="{% url 'events:list_all' %}" class="download">List Tours</a></li>
          <li><a href="/admin/" class="download">Django Admin</a></li>
          <li><a href="" class="download">_________</a></li>
          <li><a href="" class="download">_________</a></li>
          <li><a href="" class="download">_________</a></li>
          <li><a href="" class="download">_________</a></li>
        </ul>
      </nav> <!-- end Sidebar -->

      <!-- content BUTTON sidebar -->
      <!-- CONTENT -->
      <div id="content">
        <!-- took out navbar-default -->
        <nav class="navbar">
            <button type="button" id="sidebarCollapse" class="btn btn-info navbar-btn">
              <i class="glyphicon glyphicon-align-left"></i>
            </button>
        </nav>

        <!-- content BLOCK -->
        <div id="shellblock">
          <div id="contentheader">
            {% block contentheader %}
            {% endblock %}
          </div>
          {% block content %}
          {% endblock %}
        </div>
      </div> <!--end CONTENT -->

    </div>
  </body>

</html>

MOSTregi/templates/index_old.html
<html>
{% load staticfiles %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}
  <head>
    <!-- css -->
    <link rel="stylesheet" href="{% static '/css/index.css' %}">
    <!-- jquery -->
    <script type="text/javascript" src="{% static '/js/jquery-3.3.1.js' %}"></script>
    <!-- favicon -->
    <link rel="shortcut icon" type="image/png" href="{% static '/img/favicon/favicon.ico' %}"/>
    <!-- handles sidebar collapse -->
    <script type="text/javascript">
      $(document).ready(function () {
        $('#sidebarCollapse').on('click', function () {
        $('#sidebar, #content').toggleClass('active');
        $('.collapse.in').toggleClass('in');
        $('a[aria-expanded=true]').attr('aria-expanded', 'false');
        });
      });
    </script>
    <!-- html boilerplate stuff -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Museum of South Texas History</title>
  </head>

  <body>
    <!-- wrapper holds entire page -->
    <!-- (I don't remember why I did this but it's not hurting anything) -->
    <div class="wrapper">
      <!-- Sidebar Holder -->
      <nav id="sidebar">
        <div id="sidebar-header">
          <h3><b>MOST History</b></h3>
        </div>

        <ul class="list-unstyled components">
          <li>
          <!-- <li class="active"> -->
            <a href="/home/" data-toggle="collapse">Home</a>
          </li>
          <li>
            <a href="/form/">Visit Us</a>
          </li>
          <li>
            <a href="/exhibits/">Exhibitions</a>
          </li>
          <li>
            <a href="/collections/">Collections</a>
          </li>
          <li>
            <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false">broken submenu.<br>mommy will fix you soon. <3</a>
            <ul class="collapse list-unstyled" id="pageSubmenu">
              <li><a href="#">Page 1</a></li>
              <li><a href="#">Page 2</a></li>
              <li><a href="#">Page 3</a></li>
            </ul>
          </li>
       </ul>
          <ul class="list-unstyled CTAs">
            <li><a href="/admin/" class="download">Admin</a></li>
            <!-- <li><a href="/login/" class="download">Login</a></li>
            {% if user.is_authenticated %}
              <li>User: {{ user.get_username }}</li>
              <li><a href="/logout/" class="download">Logout</a></li>
            {% else %}
              <li>user.us_authenticated is false!</li>
            {% endif %} -->
            <li><a href="{% url 'events:new' %}" class="download">Register (demo event model)</a></li>
          </ul>
      </nav> <!-- end Sidebar -->

      <!-- CONTENT -->
      <div id="content">

        <!-- content BUTTON sidebar -->
        <nav class="navbar navbar-default">
            <button type="button" id="sidebarCollapse" class="btn btn-info navbar-btn">
              <i class="glyphicon glyphicon-align-left"></i>
              <!-- <span>Toggle Sidebar</span>-->
            </button>
        </nav>

        <!-- content TITLE -->
        <h3 id="museum-title">
          Museum of South Texas History
        </h3><br>

        <!-- content BLOCK -->
        {% block content %}
        <div class="line"></div>
        <h2>default load page bby :*</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <div class="line"></div>
        {% endblock %}
      </div> <!--end CONTENT -->

    </div>
  </body>

</html>