MOSTregi/MOSTregi/urls.py
# MOSTregi/urls

from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls import url
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView, TemplateView
from django.contrib.auth import views as auth_views

from . import views
from users import views as users_views

urlpatterns = [
    re_path(r'^favicon.ico$',
        RedirectView.as_view(
            url=staticfiles_storage.url('img/favicon/favicon.ico'),
            permanent=False),
        name="favicon"
    ),
    re_path(r'^$', TemplateView.as_view(template_name='home.html')),
    path('home/', TemplateView.as_view(template_name='home.html')),
    re_path(r'^admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', users_views.signup.as_view(), name='signup'),
    path('events/', include('events.urls', 'events')),
]

# =============================================
#  code graveyard
# =============================================
# from django.conf import settings
# from os import listdir, walk
# from os.path import *
#
# def files_from_dir(directory):
#     result = []
#     for root, directories, filenames in walk(directory):
#         for directory in directories:
#             print()
#         for filename in filenames:
#             result.append(filename)
#     return result
#
# def files_from_list_of_dir(dir_list):
#     result = []
#     if not dir_list:
#         return result
#     for folder in dir_list:
#         print("calling files_from_dir on ", folder)
#         result.extend(files_from_dir(folder))
#     return result

# what we actually want to do is generate a list of static files that end in .html
# and if (w/e).html fits it, call views.fetchHTML

MOSTregi/events/urls.py
# django imports
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls import url
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

# local imports
from . import views

app_name = 'events'

urlpatterns = [
    path('', views.events_landing, name="events_landing"),
    path('new/', views.new, name="new"),
    re_path(r'edit/(?P<pk>\d+)/', views.edit, name="edit"),
    re_path(r'delete/(?P<pk>\d+)/', views.delete, name="delete"),
    path('delete_all/', views.delete_all, name="delete_all"),
    re_path(r'show_detail/(?P<pk>\d+)/', views.show_detail, name="show_detail"),
    path('all/', views.list_all, name="list_all"),
    path('all/mine/', views.list_mine, name="list_mine"),
    #re_path(r'^([a-zA-Z/]{0,50})$', views.testCatch),
]

MOSTregi/users/urls.py
# MOSTregi/urls

from django.urls import path, re_path, include

urlpatterns = [

]

MOSTregi/events/models.py
# external dependency
from phonenumber_field.modelfields import PhoneNumberField

# python imports
import datetime
from functools import partial

# django imports
from django.db import models
from django.db.models import DateTimeField
from django.core.validators import MaxValueValidator, MinValueValidator, EmailValidator
from django.utils import timezone
from django.conf import settings
from django.contrib.auth.models import User

class AutoDateTimeField(models.DateTimeField):
    def pre_save(self, model_instance, add):
        # print("in AutoDateTimeField: datetime.now:", str(timezone.now()))
        return timezone.now()

def current_hour(addhours = 0):
    now = datetime.datetime.now() + datetime.timedelta(hours=addhours)
    return datetime.time(now.hour, now.minute)

class BookingRequest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=40,)
    date_time_received = AutoDateTimeField('booked on', default=timezone.now)
    email = models.CharField(max_length=40, validators=[EmailValidator])
    telephone = PhoneNumberField()
    #date_request = models.DateField('date requested', default=seven_days_later())
    date_request = models.DateField('date requested')
    # arrival_time = models.TimeField('arrival time', default=current_hour)
    # departure_time = models.TimeField('departure time', default=partial(current_hour, addhours=1))
    arrival_time = models.TimeField('arrival time')
    departure_time = models.TimeField('departure time')
    number_attending = models.IntegerField(
        default = 1, validators=[MaxValueValidator(50), MinValueValidator(1)]
    )
    school = models.CharField(max_length=50, blank=True)
    class Meta:
        verbose_name = 'visitor registration'
        verbose_name_plural = 'visitor registrations'
    def save(self, *args, **kwargs):
        if self.user is None:
            self.user = User.objects.get(id=1)
        super(BookingRequest, self).save(*args, **kwargs)

    def __str__(self):
        return "%s, booked on %s, for %s%s" % (self.name,
            self.date_time_received.strftime("%d.%m.%Y"),
            self.date_request.strftime("%d.%m.%Y "),
            self.arrival_time.strftime("%I:%M%p"),
        )
    def is_upcoming(self):
        date_and_time = datetime.datetime.combine(self.date_request, self.time_request)
        return date_and_time >= timezone.now()

# notes:
# we can do one-to-one, many-to-one, etc using django's ForeignKey field.

MOSTregi/events/forms.py
# python imports
import datetime
from functools import partial

# django imports
from django import forms
from django.conf import settings

# project imports
from .models import BookingRequest
from .select_time_widget import SelectTimeWidget

def current_hour(addhours = 0):
    now = datetime.datetime.now() + datetime.timedelta(hours=addhours)
    return datetime.time(now.hour, now.minute)

def default_hour(hour=9, addhours = 0):
    time = datetime.datetime(2000, 1, 1, hour, 0) + datetime.timedelta(hours=addhours)
    return time.time

class DateInput(forms.DateInput):
    input_type = 'date'

class BookingRequestForm(forms.ModelForm):
    class Meta:
        model = BookingRequest
        fields=('name',
                'email',
                'telephone',
                'date_request',
                'arrival_time',
                'departure_time',
                'number_attending',
                'school')
        widgets = {
            'date_request': DateInput(),
            'arrival_time': SelectTimeWidget(twelve_hr=True, use_seconds=False, minute_step=30),
            'departure_time': SelectTimeWidget(twelve_hr=True, use_seconds=False, minute_step=30),
        }

    def __init__(self, *args, **kwargs):
        super(BookingRequestForm, self).__init__(*args, **kwargs)
        self.fields['date_request'].initial = datetime.date.today
        self.fields['arrival_time'].initial = default_hour()
        self.fields['departure_time'].initial = default_hour(addhours=1)
        if settings.DEBUG :
            self.fields['name'].initial = "Danny Devito"
            self.fields['email'].initial = "dannydevito2@paddys.com"
            self.fields['telephone'].initial = "646 301 2333"
            self.fields['school'].initial = "Potsdamn"
        #     self.fields['arrival_time'].initial = current_hour
        #     self.fields['departure_time'].initial = partial(current_hour, addhours=1)

# vvv replaced by SelectTimeWidget!
# the appareance is browser dependent!!
#class TimeInput(forms.TimeInput):
#    input_type = 'time'

MOSTregi/events/views.py
# django imports
from django.shortcuts import redirect, render, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required, permission_required
from django.core.mail import send_mail
from django.template.loader import get_template
from django.template import Context

# project imports
from .models import BookingRequest
from .forms import BookingRequestForm

def show_detail(request, pk):
    event = event = get_object_or_404(BookingRequest, pk=pk)
    return render(request, 'events/event_detail.html', {'event': event})

def list_all(request):
    events = BookingRequest.objects.all().order_by('-date_time_received')
    return render(request, 'events/event_list.html', {'events': events})

@login_required(login_url='/login/')
def list_mine(request):
    events = BookingRequest.objects.filter(user=request.user).order_by('-date_time_received')
    return render(request, 'events/event_list_mine.html', {'events': events})

@login_required(login_url='/login/')
@permission_required('events.add_bookingrequest', raise_exception=True)
def new(request):
    if request.method == "POST":
        form = BookingRequestForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            email_template = get_template('events/confirmation_email.txt')
            email_message = email_template.render({'event': post})
            send_mail('Subject Test',
                      email_message,
                      'from@mostregi.net',
                      [post.email],
                      fail_silently=False )
            return redirect('events:show_detail', pk=post.pk)
        else:
            print("form not valid, form errors: %s, form is bound: %s" % (form.errors.as_data(), form.is_bound))
            data=request.POST.get('date_request')
            print(data)
    else:
        form = BookingRequestForm
    return render(request, 'events/new.html', {'form': form})

def delete_all(self):
    try:
        BookingRequest.objects.all().delete()
        return redirect('events:list_all')
    except BookingRequest.DoesNotExist:
        return render(request, 'error.html', {'error': "Forms already deleted."})

@login_required(login_url='/login/')
@permission_required('events.delete_bookingrequest', raise_exception=True)
def delete(request, pk):
    if not request.user.is_authenticated:
        return render(request, 'error.html', {'error': "Permission Denied. Please log in before deleting."})
    try:
        event = BookingRequest.objects.get(pk=pk)
        deletetion_collector = event.delete()
        form = BookingRequestForm
        # INCOMPLETE: we want to give confirmation of delete, then add a new form.
        return redirect('events:list_all')
    except BookingRequest.DoesNotExist:
        return render(request, 'error.html', {'error': "Form already deleted."})

@login_required(login_url='/login/')
@permission_required('events.change_bookingrequest', raise_exception=True)
def edit(request, pk):
    event = get_object_or_404(BookingRequest, pk=pk)
    if request.method == "POST":
        form = BookingRequestForm(request.POST, instance=event)
        if form.is_valid():
            post = form.save(request.POST)
            post.save()
            return redirect('events:show_detail', pk=post.pk)
        else:
            print("form not valid, form errors: %s, form is bound: %s" % (form.errors.as_data(), form.is_bound))
            data=request.POST.get('date_request')
            print(data)
    else:
        form = BookingRequestForm(instance=event)
    return render(request, 'events/new.html', {'form': form})

def events_landing(request):
    html = "<html><body><h1> landing page </h1></body></html>"
    return HttpResponse(html)

MOSTregi/templates/events/__blank_landing.html
{% extends 'index.html' %}

{% load staticfiles %}

{% block extrahead %}
<link rel="stylesheet" href="{% static '/css/new.css' %}">
{% endblock %}

{% block contentheader %}
<h1 style="font-family: 'Playfair Display', serif;"></h1>
{% endblock %}

{% block content %}
<html>
    <h1>Blank landing page!</h1>
    <p>You shouldn't be here...</p>
</html>

{% endblock %}

MOSTregi/templates/events/event.html
<table>
  <tr>
    <th>Booked by:</th>
    <th>{{ event.name }}</th>
  </tr>
  <tr>
    <th>Email:</th>
    <th>{{ event.email }}</th>
  </tr>
  <tr>
    <th>Phone number:</th>
    <th>{{ event.telephone }}</th>
  </tr>
  <tr>
    <th>Received on:</th>
    <th>{{ event.date_time_received }}</th>
  </tr>
  <tr>
    <th>Date requested:</th>
    <th>{{ event.date_request }}</th>
  </tr>
  <tr>
    <th style="padding: 0 20px 0 0;">Time Requested:</th>
    <th>{{ event.arrival_time }} - {{ event.departure_time }}</th>
  </tr>
  <tr>
    <th># Attending:   </th>
    <th>{{ event.number_attending }}</th>
  </tr>
  <tr>
    <th>School:</th>
    <th>{{ event.school }}</th>
  </tr>
</table>

<p>Posted by {{ event.user }}, on {{ event.date_time_received }}<br></p>
<a class="btn btn-default" id="edit_button" href="{% url 'events:edit' pk=event.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
<a class="btn btn-default" id="delete_button" href="{% url 'events:delete' pk=event.pk %}"><span class="glyphicon glyphicon-trash"></span></a>

MOSTregi/templates/events/event_detail.html
{% extends 'index.html' %}
{% load staticfiles %}

{% block extrahead %}
<link rel="stylesheet" href="{% static '/css/event_detail.css' %}">
{% endblock %}

{% block contentheader %}
<h1 style="font-family: 'Playfair Display', serif;">Booking received!</h1>
{% endblock %}

{% block content %}
<div class="event_detail">
  {% include 'events/event.html' %}
  <a class="btn btn-default" href="{% url 'events:new' %}"><span class="glyphicon">New</span></a>
</div>

{% endblock %}

MOSTregi/templates/events/event_list.html
{% extends 'index.html' %}

{% load staticfiles %}

{% block extrahead %}
<link rel="stylesheet" href="{% static '/css/event_list.css' %}">
{% endblock %}

{% block contentheader %}
<h1 style="font-family: 'Playfair Display', serif;">Currently Registered:</h1>
{% endblock %}

{% block content %}
<html>
<a class="btn btn-default" id="delete_all_button" href="{% url 'events:delete_all' %}"><span class="glyphicon glyphicon-trash">All</span></a>
{% for event in events %}
<div class="event_detail">
  {% include 'events/event.html' %}
</div>
{% endfor %}
</html>

{% endblock %}

MOSTregi/templates/events/event_list_mine.html
{% extends 'index.html' %}

{% load staticfiles %}

{% block extrahead %}
<link rel="stylesheet" href="{% static '/css/event_list.css' %}">
{% endblock %}

{% block contentheader %}
<h1 style="font-family: 'Playfair Display', serif;">Currently Registered:</h1>
{% endblock %}

{% block content %}
<html>
{% for event in events %}
<div class="event_detail">
  {% include 'events/event.html' %}
</div>
{% endfor %}
</html>

{% endblock %}

MOSTregi/templates/events/new.html
{% extends 'index.html' %}

{% load staticfiles %}

{% block extrahead %}
<link rel="stylesheet" href="{% static '/css/new.css' %}">
{% endblock %}

{% block contentheader %}
<h1 style="font-family: 'Playfair Display', serif;">New Booking:</h1>
{% endblock %}

{% block content %}
<html>
    <!-- <h1 style="padding: 0 0 20px; color: hsl(0, 0%, 30%);">New Booking</h1> -->
    <form method="POST" class="post-form">{% csrf_token %}
      <table>
        {{ form }}
      </table>
        <button type="submit" class="save btn btn-default">Save</button>
    </form>

</html>

{% endblock %}